tailwind.config = {
    darkMode: "class",
    theme: {
      extend: {
        colors: {
          "inverse-on-surface": "#9c9d9f",
          "on-surface": "#2d3338",
          "primary-fixed-dim": "#d4d4d4",
          "error": "#9e3f4e",
          "surface-tint": "#5e5e5e",
          "background": "#f9f9fb",
          "on-primary-fixed": "#3f3f3f",
          "outline": "#757c81",
          "on-surface-variant": "#596065",
          "surface-container": "#ebeef2",
          "surface-container-lowest": "#ffffff",
          "tertiary-fixed": "#f4f3f8",
          "on-tertiary": "#faf8fe",
          "secondary-fixed": "#e4e2e5",
          "on-tertiary-fixed-variant": "#65666a",
          "secondary-dim": "#535356",
          "secondary": "#5f5f62",
          "primary-container": "#e2e2e2",
          "on-tertiary-fixed": "#49494e",
          "surface-container-highest": "#dde3e9",
          "tertiary": "#5e5f63",
          "inverse-primary": "#ffffff",
          "surface-variant": "#dde3e9",
          "on-error": "#fff7f7",
          "on-background": "#2d3338",
          "surface-dim": "#d3dbe2",
          "primary": "#5e5e5e",
          "on-secondary": "#faf8fc",
          "tertiary-dim": "#525357",
          "surface-container-low": "#f2f4f6",
          "surface-container-high": "#e4e9ee",
          "error-container": "#ff8b9a",
          "on-secondary-container": "#525154",
          "tertiary-container": "#f4f3f8",
          "on-secondary-fixed-variant": "#5b5b5e",
          "error-dim": "#4f0116",
          "tertiary-fixed-dim": "#e6e5ea",
          "primary-dim": "#525252",
          "outline-variant": "#acb3b8",
          "on-primary": "#f8f8f8",
          "on-error-container": "#782232",
          "secondary-fixed-dim": "#d6d4d7",
          "secondary-container": "#e4e2e5",
          "primary-fixed": "#e2e2e2",
          "on-primary-fixed-variant": "#5b5b5b",
          "on-secondary-fixed": "#3f3f42",
          "on-tertiary-container": "#5b5b60",
          "surface": "#f9f9fb",
          "on-primary-container": "#525252",
          "surface-bright": "#f9f9fb",
          "inverse-surface": "#0c0e10"
        },
        fontFamily: {
          "headline": ["Inter"],
          "body": ["Inter"],
          "label": ["Inter"]
        },
        borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
      },
    },
};
